GET http://localhost:3000/test

###

GET http://localhost:3000/test/65108f0db5e9b3508666baf6

###

POST http://localhost:3000/test
Content-Type: application/json

{
    "name": "test",
    "age": 16
}

###